import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useContext } from "react";
import { LoginUserContext, LoginUserProvider } from "./userContext";
import { UserContextType } from "./types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ユーザ情報をどこでも使えるようLoginUserProviderで設定する
    <LoginUserProvider>
      <html lang="en">
        <body>
          <div className="all-todo">
            <div className="container">
              {children}
            </div>
          </div>
        </body>
      </html>
    </LoginUserProvider>
  );
}
