import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoginUserProvider from "./components/Auth/LoginUserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 現在ログインしているか常時監視→LoginStateConfirmation
    <LoginUserProvider>
      <html lang="en">
        <body>
          <div className="all-todo">
            <div className="container">
              {children}
            </div>
          </div>
        </body>
      </html>
    </LoginUserProvider>
  );
}
